# build pykdtree wheels for PyPi

variables:
  package_name: pykdtree

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

# Build multiple version of python linux wheels in single job.  
# As we have to start docker and download a docker image, it's more
# efficient to have multiple builds on one image, especially
# considering we share this with pyvista.
jobs:
- job: Linux
  strategy:
    matrix:
      64Bit2010:
        arch: x86_64
        plat: manylinux2010_x86_64
        image: quay.io/pypa/manylinux2010_x86_64
        python.architecture: x64  
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
      displayName: 'Use Python $(python.version)'
    - script: |
        set -ex
        docker run -e PLAT=$(plat) -e package_name=$(package_name) --rm -v `pwd`:/io $(image) /io/.ci/build_wheels.sh
        ls -lh wheelhouse/
        mkdir -p dist
        # cheat by renaming file to manylinux1 (even though it's really 2010)
        cd wheelhouse
        find . -type f -name '$(package_name)-*' | while read FILE ; do
          NEWFILE="$(echo ${FILE} |sed -e 's/\linux/manylinux1/')"
          cp "${FILE}" ../dist/"${NEWFILE}" ;
        done 
        cd ..
      displayName: Build wheels
    - template: .ci/azure-publish-dist.yml


- job: macOS
  variables:
    python.architecture: 'x64'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  pool:
    vmImage: 'macOS-10.14'
  steps:
    - script: .ci/macos-install-python.sh '$(python.version)'
      displayName: Install Python
    - template: .ci/azure-setup.yml
    - template: .ci/azure-steps.yml
    - template: .ci/azure-publish-dist.yml


- job: Windows
  pool:
    vmIMage: 'VS2017-Win2016'
  variables:
    python.architecture: 'x64'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  steps:
    - template: .ci/azure-setup.yml
    - template: .ci/azure-steps.yml
    - template: .ci/azure-publish-dist.yml